### ISSUE TITLE
disable pytest when unrelated files changed

### ISSUE THREAD

**Issue by pchalasani** [langroid/langroid#261]
I have this in the `.github/workflows/pytest.yml`:

```
name: Pytest

on:
  push:
    paths-ignore:
      - "docs/**"
      - "mkdocs.yml"
    branches:
      - main  # Replace with your default branch name 
  pull_request:
    branches:
      - main  # Replace with your default branch name
```

which I thought will ensure this workflow is not run when only `docs/` change. But it still runs.
Need a fix.
